<template>
  <div id="app">
    <router-view></router-view>
  </div>
</template>

<script>
  export default {
    name: 'electron'
  }
</script>

<style>

  /** Generated by FG **/
  @font-face {
    font-family: 'Conv_7fonts.ru_Digit';
    src: url('./assets/fonts/7fonts.ru_Digit.eot');
    src: local('☺'), url('./assets/fonts/7fonts.ru_Digit.woff') format('woff'), url('./assets/fonts/7fonts.ru_Digit.ttf') format('truetype'), url('./assets/fonts/7fonts.ru_Digit.svg') format('svg');
    font-weight: normal;
    font-style: normal;
  }

  body {
    width: 500px;
    margin: 0;
  }

 body * {
   box-sizing: border-box;
 }

  button svg {
    fill: currentColor;
    width: 15px;
    height: 15px;
  }
  button {
    display: inline-flex;
    justify-content: center;
    align-items: center;
  }
  input[readonly]{
    background-color: #ececec;
    border-color: #ececec!important;
  }

</style>
